import json
import argparse
from pathlib import Path

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans


def get_output_filename(tag_type: str, target_level: str) -> str:
    if tag_type not in {"functions", "use_cases"}:
        raise ValueError(f"Unsupported tag type: {tag_type}")

    if target_level == "secondary":
        return f"clustered_{tag_type}_output.json"

    if target_level == "primary":
        return f"clustered_{tag_type}_primary_output.json"

    raise ValueError(f"Unsupported target level: {target_level}")


def main():
    # 2. Parse command-line arguments
    parser = argparse.ArgumentParser(
        description="Cluster unique tags using semantic embeddings and K-Means."
    )

    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Input JSON file containing unique tags.",
    )

    parser.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help="Directory for clustered JSON outputs.",
    )

    parser.add_argument(
        "--k",
        required=True,
        type=int,
        help="Number of K-Means clusters.",
    )

    parser.add_argument(
        "--tag-type",
        required=True,
        choices=("functions", "use_cases"),
        help="Taxonomy represented by the input tags.",
    )

    parser.add_argument(
    "--target-level",
    required=True,
    choices=("secondary", "primary"),
    help="Taxonomy level generated by this clustering run.",
    )

    args = parser.parse_args()

    # 3. Build input/output paths
    input_path = args.input

    output_path = args.output_dir / get_output_filename(
    args.tag_type,
    args.target_level,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # 4. Validate input file
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    # 5. Read JSON file
    print(f"Reading file from: {input_path}")

    with input_path.open("r", encoding="utf-8") as f:
        records = json.load(f)

    if args.target_level == "secondary":
        tags = [record["tag"] for record in records]

    elif args.target_level == "primary":
        tags = [
            secondary_tag_record["secondary_tag"]
            for pocket in records
            for secondary_tag_record in pocket["secondary_tags"]
        ]

    print(f"Successfully loaded {len(tags)} tags!")

    # 6. Load semantic model and generate embeddings
    print(
        "Loading semantic model (all-MiniLM-L6-v2) "
        "and generating embeddings..."
    )

    model = SentenceTransformer("all-MiniLM-L6-v2")

    embeddings = model.encode(
        tags,
        show_progress_bar=True
    )

    print(f"Embedding complete! Matrix shape: {embeddings.shape}")

    # 7. Perform K-Means clustering
    n_clusters = args.k

    print(
        f"Running K-Means clustering into "
        f"{n_clusters} pockets..."
    )

    kmeans = KMeans(
        n_clusters=n_clusters,
        random_state=42,
        n_init=10
    )

    cluster_labels = kmeans.fit_predict(embeddings)

    # 8. Build cluster output
    clusters_data = {}
    clusters_data_no_vectors = {}

    for i in range(n_clusters):
        clusters_data[f"pocket_{i}"] = {
            "pocket_id": i,
            "items": []
        }

        clusters_data_no_vectors[f"pocket_{i}"] = {
        "pocket_id": i,
        "items": []
        }

    for tag, label, embedding in zip(
        tags,
        cluster_labels,
        embeddings
    ):
        # Full version: keep embedding vector
        clusters_data[f"pocket_{label}"]["items"].append({
            "tag": tag,
            "vector": embedding.tolist()
        })

        # Lightweight version: tag only
        clusters_data_no_vectors[f"pocket_{label}"]["items"].append({
            "tag": tag
        })

    # 9. Save result
    print(f"Saving clustering results to: {output_path}")

    # Full version with vectors
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(
            clusters_data,
            f,
            ensure_ascii=False,
            indent=4
        )

    # Lightweight version without vectors
    no_vectors_output_path = (
        output_path.parent
        / f"{output_path.stem}_no_vectors.json"
    )

    with no_vectors_output_path.open("w", encoding="utf-8") as f:
        json.dump(
            clusters_data_no_vectors,
            f,
            ensure_ascii=False,
            indent=4
        )

    print("Clustering completed successfully!")
    print(f"Full output: {output_path.name}")
    print(f"No-vector output: {no_vectors_output_path.name}")


if __name__ == "__main__":
    main()
