import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Validate consolidated secondary or primary tags "
            "against their clustered input tags."
        )
    )

    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Cluster JSON file without vectors.",
    )

    parser.add_argument(
        "--consolidated-input",
        required=True,
        type=Path,
        help="Consolidated tag JSON file.",
    )

    parser.add_argument(
        "--tag-type",
        required=True,
        choices=("functions", "use_cases"),
        help="Taxonomy type represented by the input files.",
    )

    parser.add_argument(
        "--target-level",
        required=True,
        choices=("secondary", "primary"),
        help="Taxonomy level generated by consolidation.",
    )

    args = parser.parse_args()

    if not args.input.exists():
        raise FileNotFoundError(
            f"Cluster input file not found: {args.input}"
        )

    if not args.consolidated_input.exists():
        raise FileNotFoundError(
            "Consolidated input file not found: "
            f"{args.consolidated_input}"
        )

    with args.input.open("r", encoding="utf-8") as file:
        clusters = json.load(file)

    with args.consolidated_input.open(
        "r",
        encoding="utf-8",
    ) as file:
        consolidated_pockets = json.load(file)

    if args.target_level == "secondary":
        tag_list_key = "secondary_tags"
        target_tag_key = "secondary_tag"
        source_list_key = "source_tags"

        source_label = "source tag"
        target_label = "secondary tag"
    else:
        tag_list_key = "primary_tags"
        target_tag_key = "primary_tag"
        source_list_key = "source_secondary_tags"

        source_label = "secondary tag"
        target_label = "primary tag"

    consolidated_by_id = {
        pocket["pocket_id"]: pocket
        for pocket in consolidated_pockets
    }

    missing_pockets = []
    missing_tags = []
    unexpected_tags = []
    duplicate_assignments = []

    # Validate assignments inside each pocket.
    for pocket_data in clusters.values():
        pocket_id = pocket_data["pocket_id"]

        input_tags = [
            item["tag"]
            for item in pocket_data["items"]
        ]

        result = consolidated_by_id.get(pocket_id)

        if result is None:
            missing_pockets.append(pocket_id)
            continue

        assigned_tags = [
            source_tag
            for target_item in result.get(tag_list_key, [])
            for source_tag in target_item.get(
                source_list_key,
                [],
            )
        ]

        input_counter = Counter(input_tags)
        assigned_counter = Counter(assigned_tags)

        for tag in input_counter:
            if assigned_counter[tag] == 0:
                missing_tags.append(
                    (pocket_id, tag)
                )
            elif assigned_counter[tag] > 1:
                duplicate_assignments.append(
                    (
                        pocket_id,
                        tag,
                        assigned_counter[tag],
                    )
                )

        for tag in assigned_counter:
            if tag not in input_counter:
                unexpected_tags.append(
                    (pocket_id, tag)
                )

    # Check whether one source tag maps to multiple target tags.
    source_to_target = defaultdict(set)

    for pocket in consolidated_pockets:
        target_items = pocket.get(tag_list_key, [])

        for target_item in target_items:
            target_tag = target_item[target_tag_key]

            source_tags = target_item.get(
                source_list_key,
                [],
            )

            for source_tag in source_tags:
                source_to_target[source_tag].add(
                    target_tag
                )

    cross_pocket_conflicts = {
        source_tag: target_tags
        for source_tag, target_tags
        in source_to_target.items()
        if len(target_tags) > 1
    }

    taxonomy_label = (
        "functions"
        if args.tag_type == "functions"
        else "use cases"
    )

    print(
        f"Validating {taxonomy_label} at "
        f"the {args.target_level} level."
    )
    print(
        f"Missing pockets: "
        f"{len(missing_pockets)}"
    )
    print(
        f"Missing {source_label} assignments: "
        f"{len(missing_tags)}"
    )
    print(
        f"Unexpected {source_label}s: "
        f"{len(unexpected_tags)}"
    )
    print(
        "Duplicate assignments within a pocket: "
        f"{len(duplicate_assignments)}"
    )
    print(
        f"{source_label.capitalize()}s mapped to "
        f"multiple {target_label}s: "
        f"{len(cross_pocket_conflicts)}"
    )

    validation_passed = (
        not missing_pockets
        and not missing_tags
        and not unexpected_tags
        and not duplicate_assignments
        and not cross_pocket_conflicts
    )

    if validation_passed:
        print(
            "\nValidation passed: every "
            f"{source_label} maps to exactly one "
            f"{target_label}."
        )
    else:
        print(
            "\nValidation failed. "
            "Inspect the lists below:"
        )

        print(
            "\nMissing pockets:",
            missing_pockets[:10],
        )
        print(
            "Missing tags:",
            missing_tags[:10],
        )
        print(
            "Unexpected tags:",
            unexpected_tags[:10],
        )
        print(
            "Duplicate assignments:",
            duplicate_assignments,
        )
        print(
            "Cross-pocket conflicts:",
            list(
                cross_pocket_conflicts.items()
            )[:10],
        )


if __name__ == "__main__":
    main()